<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{ckanr vignette}
-->



ckanr vignette
==============

`ckanr` is an R client for the generic CKAN API - that is, plug in a base url for the CKAN instance of interest. 

## Install

This is a specialized version for DSP. 

Please install this package from github via:

```r
library(devtools)
install_github("dspim/ckan")
```

## Getting Started

```r
library("ckanr")
```

Note: the default base CKAN URL is set to [http://data.techno-science.ca/](http://data.techno-science.ca/). You can change this using `ckanr_setup()`, or change the URL using the `url` 
parameter in each function call.

To set one or both, run:


```r
# Restore to default
ckanr_setup()
# Just set url
ckanr_setup(url = "http://106.187.93.114")
# set url and key
ckanr_setup(url = "http://106.187.93.114" , key = "<put your key here>")
```

## Changes


```r
changes(limit = 2, as = "table")[, 1:4]
```

## List datasets


```r
package_list(as = "table")
```

## List tags


```r
tag_list('65', as = 'table')
```

## Show tags

Subset for readme brevity


```r
tag_show('1360339d-78e9-4188-b2c8-8f1b9e3a008a')
```

## List groups


```r
group_list(as = 'table')
```

## Show groups

Subset for readme brevity


```r
group_show('wush', as = 'table')
```

## Show a package


```r
package_show('hp03-olderman-dentual')
```

### Show the resources fetch to the package

```r
hp03 <- package_show('hp03-olderman-dentual')
hp03$resources
resource_show(hp03$resources[[1]]$id)
```

## Search for packages


```r
out <- package_search(q = '臺南市', rows = 2, as = "table")
```

## Search for resources


```r
resource_search(q = 'name:臺南市', limit = 20, as = 'table')
```

## Download Resource

```r
id <- hp03$resources[[1]]$id
ds_search(id, as = "table")
```

## Create Resource

```r
file <- system.file("examples", "actinidiaceae.csv", package = "ckanr")
head(read.csv(file))
res <- ds_create_dataset(package_id = "hp03-olderman-dentual", name = "DSP Demo ckanr Create Resource", file)
```

## Delete Resource

```r
resource_delete(res$id)
```

## Error

### CKAN Server Error

ckanr_setup(key = "")
ds_create_dataset(package_id = "hp03-olderman-dentual", name = "DSP Demo ckanr Create Resource", file)


